#pragma once

#define SPI_DISPLAY_BACKLIGHT 22
#define SPI_DISPLAY_RST 21 
#define SPI_DISPLAY_DC 20
#define SPI_DISPLAY_TX 19
#define SPI_DISPLAY_SCK 18
#define SPI_DISPLAY_CSN 17 
#define SPI_DISPLAY_RX 16

#define I2C_DISPLAY_BACKLIGHT -1
#define I2C_DISPLAY_ADDRESS 0x3C
#define I2C_DISPLAY_SDA 6
#define I2C_DISPLAY_SCL 7
